# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/deepbrainchain?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: deepbrain
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15
  data:
    mongodb:
      uri: mongodb://localhost:27017/deepbrainchainlocal
      database: deepbrainchain
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 11
    timeout: 15000
    pool:
      max-active: 600
      max-idle: 300
      max-wait: -1
  devtools:
    restart:
      enabled: false # disable on prod environment
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload

# ===================================================================
# Application specific properties
# ===================================================================
application:
  jenkins:
    admin-url: http://192.168.20.18:2010
  file-ftp:
    url: 172.31.29.217
    userName: hp
    password: Hp#!Pl379AZ
    uploadDir: prod
    httpUrl: https://hp.deepbrainchain.org
    kycImagUrlPrefix: https://info.deepbrainchain.org/
  url:
    bountyUrl: https://www.deepbrainchain.org/bounty.html
    signUpUrl: https://www.deepbrainchain.org/dptlanding.html?nologin=1
    minerSignUpUrl: https://www.deepbrainchain.org/index.html?nologin=1
  eth:
    rpcUrl: http://172.31.25.139:8558
  neo:
    rpcUrl: http://172.31.23.114:10332
